image: ubuntu:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - apt-get update -yqq
  - apt-get install -yyq shellcheck

test:
  script:
    - shellcheck wsl-open.sh
    - test/bats/bin/bats test/
