image: ubuntu:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - apt-get update -yqq
  - apt-get install -yqq npm git wget

test:
  script:
    - npm install --unsafe-perm=true
    - npm run lint:sh
    - npm run lint:md
    - npm run unit
