image: ubuntu:latest

include:
  - template: Code-Quality.gitlab-ci.yml
  - template: Dependency-Scanning.gitlab-ci.yml
  - template: License-Scanning.gitlab-ci.yml

before_script:
  - apt-get update -yqq
  - apt-get install -yqq npm nodejs git wget

test:
  script:
    - npm install --unsafe-perm=true
    - npm run lint:pkg
    - npm run unit
  artifacts:
    paths:
      - npm-debug.log
    expire_in: 1 month
